### ISSUE TITLE
fix wac serialization

### ISSUE THREAD

**Issue by chicco785** [orchestracities/anubis#70]
**Describe the bug**
generated wac have the following limitation:
1. prefix namespace is not generated, while it should be. it would be good for example that the prefix is generated from the tenant name.
1. the base path to the resource is hard coded, while it should be configurable (and eventually even per tenant & resourceType)

```
        @prefix acl: <http://www.w3.org/ns/auth/acl#> .
        @prefix example: <http://example.org/> .

        example:a0be6113-2339-40d7-9e85-56f93372f279 a acl:Authorization ;
            acl:accessTo <http://example.org/*> ;
            acl:agentClass <acl:AuthenticatedAgent> ;
            acl:mode <acl:Write> .
```

**Comment by chicco785** [comment]
```
- default:
   - prefix: prefixName
   - baseUrl: https://myBase.url
   - resourceTypeUrls:
      - entity:
        - url: https://myorion.org/v2/entities
      - entityType:
        - url: https://myorion.org/v2/types
       - policy:
        - url: https://myanubis.org/v1/policies
 - Tenant1:
   - prefix: prefixNameTenant1
   - baseUrl: https://myBase.url
   - resourceTypeUrls:
      - entity:
        - url: https://myorion.org/v2/entities
      - entityType:
        - url: https://myorion.org/v2/types
       - policy:
        - url: https://myanubis.org/v1/policies
 ```


=>>>

```
        @prefix acl: <http://www.w3.org/ns/auth/acl#> .
        @prefix prefixName: <https://myBase.url/> .

        example:a0be6113-2339-40d7-9e85-56f93372f279 a acl:Authorization ;
            acl:accessTo <https://myorion.org/v2/entities/*> ;
            acl:agentClass <acl:AuthenticatedAgent> ;
            acl:mode <acl:Write> .
```
